### ISSUE TITLE
Need aggregate license in DESCRIPTION

### ISSUE THREAD

**Issue by hadley** [gagolews/icudt#2]
e.g. `License: BSD-3 + file LICENSE` otherwise CRAN won't accept it

**Comment by gagolews** [comment]
I had  several fix-LICENCE-issues iterations of early CRAN versions of stringi, I think that the safest approach here is to copy-paste stringi's `Licence:`

Quoting Kurt Hornik @ 2014-02-19

> - Finally, the license situation seems a bit awkward.
> 
> You seem to combine a variety of BSD-style licenses, but these do not
> seem to accumulate conveniently into a single common BSD license for the
> whole package, and certainly "stringi is itself released under the MIT
> license" does not seems appropriate.
> 
> The simplest solutions seems for you to use
> 
>   License: file LICENSE
> 
> in DESCRIPTION (with the licenses of all components represented
> correctly), and then we mark the package as FOSS on our end.
> 
> Pls also note that the copyrights listed in inst/COPYRIGHTS do not agree
> with those listed in LICENSE.

Then they just've overridden LICENSE_IS_FOSS. That did the trick.

**Comment by hadley** [comment]
Wow, I'm really surprised that they special cased that for you!
