### ISSUE TITLE
install recuires github access

### ISSUE THREAD

**Issue by drmowinckels** [gagolews/icudt#4]
I'm having issues because the newest install for stringi (and thus tidyverse) requires access to github to complete.

I work on a secure server without internet connection, and the IT are regularly duplicating the *entire* CRAN library into the server so we can work. However, since this install grabs things from github upon install, we cannot use it on the server it seems.

**Comment by gagolews** [comment]
see https://stackoverflow.com/questions/31942322/how-to-install-stringi-from-local-file-absolutely-no-internet-access
